### PR TITLE
Fix bugs & Made code look better

### PR DESCRIPTION
**Pull request by oukkat**

### CODE REVIEW

**Comment by jcreek** [comment]
Hi @oukkat,

Thanks for the PR! Unfortunately your commit is incredibly vague with no description so I'm going to have to close this PR without merging it. Feel free to submit a new PR with multiple commits. 

If you're fixing bugs, have one commit for each fix and clearly state what the bug being fixed is. If you're making the code look better, make one commit for each type of improvement (e.g. Use interpolation instead of string concatenation).

Happy new year! 

jcreek

**Comment by ssolson** [comment]
The changes are really obvious if you check the Files changed tab. 
image

What he did was add commas in the embed call. Currently, the main version will fail here. This is clearly a bug. Secondly he just used f-strings. I would merge this PR.

image

**Comment by ssolson** [comment]
Okay from reading more PRs it is clear that this is intended to run on outdated code on a docker-machine. This was not clear to me in the README.

**Comment by jcreek** [comment]
Hi @ssolson,

I'll tackle your comments in order. Firstly, whether or not it's clear from looking at the Files Changed tab, multiple changes were made in a single commit, which is undesirable, and the commit message was, as previously stated, incredibly vague with no description. I would have expected to see two commits here, one entitled something like 'Add commas to end of lines' and one like 'Replace string concatenation with interpolation', which makes it immediately obvious what has been done in each commit at a glance without having to look through code. On this basis I rejected the PR. It's worth noting that there are no bugs in the main version here. 

Secondly, if you direct your gaze to the top of the README you will see my update from November 2019, wherein I stated that this is now a Dockerised project and requires specific versions of Python and Discord.py to work. I have included a highlighted screenshot below for your convenience. 

image

I believe there are forks that use the updated versions of Python and Discord.py, which sound like they may be of more interest to you. Alternatively, you're welcome to create a fork yourself. My recommended tool for creating Discord bots these days is Discord.js so I am not updating these Python bots. Take a look at my other repos if you want to see what the Discord.js code looks like. 

Happy coding! 

jcreek

**Pull request closed without merging**
