### PR TITLE
Add leave messages and embeds

### PR DESCRIPTION
**Pull request by thrzl**
Added Embeds and a quick ID overview, added leave messages

### CODE REVIEW

**Comment by jcreek** [comment]
This is still a draft PR so cannot be merged, was there something else you wanted to do with this @isigebengu-mikey ?

**Comment by jcreek** [comment]
@isigebengu-mikey I think all the changes in this were in your other PR, so I'm closing this one. If I'm wrong then feel free to stick another PR in!

**Comment by thrzl** [comment]
Sorry about that! I'm still kind of new to Git, I didn't know you could see this.

**Comment by jcreek** [comment]
No worries - you've done a great job 😃

**Pull request closed without merging**
